version: '3'

services:
   # Backend
  api:
    build: .
    restart: always
    container_name: api
    expose:
      - 4000
    ports:
      - 4000:4000
    volumes:
      - ./:/usr/src/api/
    command: npm run start