version: '3'

services:
   # Backend
  api:
    build: .
    restart: always
    expose:
      - 4000
    env_file:
      - .env
    ports:
      - 4000:4000
    volumes:
      - ./:/usr/src/api/
    command: npm run start